apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: dawbed/react-cub  
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  selector:
    app: node
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 3000